### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by mmtech2012** [whitescent/Mastify#58]
Thanks for your beautiful application.
It seems UI dosen't support Right-To-Left language.

**Comment by whitescent** [comment]
Hi, thanks for your favorites!
mastify just supports English and Chinese now, because localization is a tedious task, after that I will plan to ask for help in translating all the texts of the App on some localization management platforms, and if you are interested you can also participate in translating the

**Comment by whitescent** [comment]
I see, can you copy the text above for me?

**Comment by ahangarha** [comment]
Please consider bidirectional text support and not just RTL.

Many people create content in mixed languages of both RTL and LTR. Many more follow accounts that create content in mixed languages. A client should be able to render the content in the proper direction regardless of the overall direction of the surrounding layout.

**Comment by lazzzis** [comment]
Adding `textDirection = TextDirection.Content` should quickly fix the issue. The remaining issue is if this should also be applied to the user's display name, bio, and so on.
