### ISSUE TITLE
Stuttery timeline when loading

### ISSUE THREAD

**Issue by LucasGGamerM** [whitescent/Mastify#72]
Mastify lags a lot when scrolling, which I believe is due to the image loading part of the app doing networking operations IO on the UI thread, causing the app to stutter. 

A possible solution would be using callbacks to only render the timeline and the subsequent images when they are fully loaded

**Comment by whitescent** [comment]
Hi @LucasGGamerM thanks for ur research and testing, The image loading part is basically done using Coil, and the [AsyncImage](https://coil-kt.github.io/coil/compose/#asyncimage) in Coil should be in the IO thread by default, so I don't think the problem should be here.

Did you test in the debug version or in the release version?, the performance of the list is completely different in the release version compared to the debug version, this is due to Jetpack Compose, if there is a performance issue in the release, it is generally due to recomposition.

I've tested list performance in the release version, and it should generally be fine (based on the values in the chart below)

![image](https://github.com/whitescent/Mastify/assets/31311826/18021217-fc98-4aea-9c16-58eee3d90d68)

**Comment by LucasGGamerM** [comment]
I can confirm that images are not the source of the issue.

After testing, I can attest that once the cache is cleaned, the app get so stuttery it's annoying. 

I am looking though the code to see what things can be done about it

**Comment by LucasGGamerM** [comment]
It seems like the issue is totally gone! I don't know what you did that made that happen, but it's awesome now
